import 'package:flutter/material.dart';

String localizedDepartmentName(BuildContext context, String value) {
  return _localizedCatalogValue(context, value, const {
    'women': 'النساء',
    'men': 'الرجال',
    'kids': 'الأطفال',
    'curve': 'كيرف',
    'beauty': 'الجمال',
    'home': 'المنزل',
    'shoes': 'الأحذية',
    'jewelry': 'المجوهرات',
    'bags': 'الحقائب',
    'electronics': 'الإلكترونيات',
    'sale': 'التخفيضات',
  });
}

String localizedCategoryName(BuildContext context, String value) {
  return _localizedCatalogValue(context, value, const {
    'dresses': 'فساتين',
    'tops': 'بلوزات',
    'bottoms': 'قطع سفلية',
    'cardigans': 'كارديغان',
    'jackets': 'جاكيتات',
    'activewear': 'ملابس رياضية',
    'sleepwear': 'ملابس نوم',
    'shirts': 'قمصان',
    't-shirts': 'تي شيرت',
    'pants': 'بناطيل',
    'shoes': 'أحذية',
    'accessories': 'إكسسوارات',
    'girls clothing': 'ملابس البنات',
    'boys clothing': 'ملابس الأولاد',
    'baby clothing': 'ملابس الرضع',
    'toys': 'ألعاب',
    'curve dresses': 'فساتين كيرف',
    'curve tops': 'بلوزات كيرف',
    'curve bottoms': 'قطع سفلية كيرف',
    'curve sets': 'أطقم كيرف',
    'curve outerwear': 'ألبسة خارجية كيرف',
    'makeup': 'مكياج',
    'skincare': 'عناية بالبشرة',
    'haircare': 'عناية بالشعر',
    'fragrance': 'عطور',
    'beauty tools': 'أدوات التجميل',
    'bedding': 'مفروشات',
    'decor': 'ديكور',
    'kitchen': 'مطبخ',
    'storage': 'تخزين',
    'lighting': 'إضاءة',
    'sneakers': 'سنيكرز',
    'heels': 'كعوب',
    'sandals': 'صنادل',
    'boots': 'بوت',
    'flats': 'أحذية مسطحة',
    'necklaces': 'قلائد',
    'rings': 'خواتم',
    'bracelets': 'أساور',
    'earrings': 'أقراط',
    'watches': 'ساعات',
    'crossbody bags': 'حقائب كروس',
    'handbags': 'حقائب يد',
    'backpacks': 'حقائب ظهر',
    'wallets': 'محافظ',
    'phone accessories': 'إكسسوارات الهاتف',
    'audio': 'صوتيات',
    'smart devices': 'أجهزة ذكية',
    'gaming': 'ألعاب إلكترونية',
    'flash sale': 'فلاش سيل',
    'clearance': 'تصفية',
    'bundle deals': 'عروض الباقات',
    'seasonal offers': 'عروض موسمية',
  });
}

String localizedSubcategoryName(BuildContext context, String value) {
  return _localizedCatalogValue(context, value, const {
    'midi dress': 'فستان ميدي',
    'maxi dress': 'فستان ماكسي',
    'mini dress': 'فستان قصير',
    'party dress': 'فستان سهرة',
    'casual dress': 'فستان كاجوال',
    'work dresses': 'فساتين عمل',
    'blouses': 'بلوزات',
    't-shirts': 'تي شيرت',
    'shirts': 'قمصان',
    'crop tops': 'بلوزات قصيرة',
    'knit tops': 'بلوزات محبوكة',
    'jeans': 'جينز',
    'wide leg pants': 'بنطال واسع',
    'skirts': 'تنانير',
    'shorts': 'شورتات',
    'leggings': 'ليغينغ',
    'underwear': 'ملابس داخلية',
    'lightweight cardigan': 'كارديغان خفيف',
    'longline cardigan': 'كارديغان طويل',
    'button cardigan': 'كارديغان بأزرار',
    'knit cardigan': 'كارديغان محبوك',
    'denim jacket': 'جاكيت جينز',
    'blazer': 'بليزر',
    'bomber': 'بومبر',
    'puffer': 'جاكيت منفوش',
    'trench': 'ترنش',
    'sports bra': 'صدرية رياضية',
    'sets': 'أطقم',
    'pajama set': 'طقم بيجاما',
    'nightdress': 'قميص نوم',
    'lounge set': 'طقم منزلي',
    'robe': 'روب',
    'formal shirt': 'قميص رسمي',
    'linen shirt': 'قميص كتان',
    'overshirt': 'أوفرشيرت',
    'printed shirt': 'قميص مطبوع',
    'basic tee': 'تي شيرت أساسي',
    'graphic tee': 'تي شيرت بطباعة',
    'oversized tee': 'تي شيرت واسع',
    'polo': 'بولو',
    'chinos': 'تشينو',
    'joggers': 'جوقر',
    'cargo pants': 'بنطال كارغو',
    'tailored pants': 'بنطال مفصل',
    'casual shoes': 'أحذية كاجوال',
    'formal shoes': 'أحذية رسمية',
    'sport shoes': 'أحذية رياضية',
    'sandals': 'صنادل',
    'belts': 'أحزمة',
    'caps': 'قبعات',
    'scarves': 'أوشحة',
    'sunglasses': 'نظارات شمسية',
    'rompers': 'رومبر',
    'outerwear': 'ألبسة خارجية',
    'kids sets': 'أطقم أطفال',
    'curve midi dress': 'فستان ميدي كيرف',
    'curve maxi dress': 'فستان ماكسي كيرف',
    'curve casual dress': 'فستان كاجوال كيرف',
    'curve blouse': 'بلوزة كيرف',
    'curve knit top': 'بلوزة محبوكة كيرف',
    'curve tee': 'تي شيرت كيرف',
    'curve jeans': 'جينز كيرف',
    'curve pants': 'بنطال كيرف',
    'curve skirt': 'تنورة كيرف',
    'co-ords': 'أطقم منسقة',
    'occasion sets': 'أطقم مناسبات',
    'curve blazer': 'بليزر كيرف',
    'curve coat': 'معطف كيرف',
    'curve jacket': 'جاكيت كيرف',
    'lipstick': 'أحمر شفاه',
    'foundation': 'فاونديشن',
    'palette': 'باليت',
    'mascara': 'ماسكارا',
    'cleanser': 'غسول',
    'serum': 'سيروم',
    'moisturizer': 'مرطب',
    'mask': 'ماسك',
    'shampoo': 'شامبو',
    'conditioner': 'بلسم',
    'hair mask': 'ماسك شعر',
    'styling': 'تصفيف',
    'perfume': 'عطر',
    'body mist': 'بودي ميست',
    'gift set': 'طقم هدايا',
    'brushes': 'فرش',
    'sponges': 'إسفنجات',
    'mirrors': 'مرايا',
    'devices': 'أجهزة',
    'sheet set': 'طقم شراشف',
    'duvet cover': 'غطاء لحاف',
    'blanket': 'بطانية',
    'pillow': 'وسادة',
    'bedding': 'مفروشات',
    'decor': 'ديكور',
    'storage': 'تخزين',
    'lighting': 'إضاءة',
    'wall art': 'لوحات جدارية',
    'vases': 'مزاهر',
    'candles': 'شموع',
    'throws': 'أغطية خفيفة',
    'storage jars': 'برطمانات تخزين',
    'cookware': 'أدوات طبخ',
    'tableware': 'أدوات مائدة',
    'utensils': 'أدوات مطبخ',
    'bins': 'سلال',
    'shelves': 'رفوف',
    'closet storage': 'تخزين دولاب',
    'boxes': 'صناديق',
    'lamp': 'مصباح',
    'string lights': 'إضاءة خيطية',
    'desk light': 'مصباح مكتب',
    'wall light': 'إضاءة جدارية',
    'running sneakers': 'سنيكرز للجري',
    'lifestyle sneakers': 'سنيكرز يومي',
    'platform sneakers': 'سنيكرز منصة',
    'block heels': 'كعب عريض',
    'pumps': 'حذاء بكعب',
    'strappy heels': 'كعب بأشرطة',
    'flat sandals': 'صندل مسطح',
    'slide sandals': 'صندل سلايد',
    'platform sandals': 'صندل منصة',
    'ankle boots': 'بوت للكاحل',
    'knee high boots': 'بوت طويل',
    'combat boots': 'بوت قتالي',
    'ballet flats': 'حذاء باليه',
    'loafers': 'لوفر',
    'mules': 'مول',
    'pendant': 'تعليقة',
    'necklaces': 'قلائد',
    'rings': 'خواتم',
    'bracelets': 'أساور',
    'earrings': 'أقراط',
    'watches': 'ساعات',
    'layered': 'متعدد الطبقات',
    'statement': 'بارز',
    'stacking rings': 'خواتم قابلة للتكديس',
    'statement rings': 'خواتم بارزة',
    'band rings': 'خواتم دائرية',
    'chain bracelet': 'سوار سلسلة',
    'cuff': 'سوار مفتوح',
    'charm bracelet': 'سوار تعليقات',
    'studs': 'أقراط صغيرة',
    'hoops': 'حلقات',
    'drops': 'متدلية',
    'classic watch': 'ساعة كلاسيكية',
    'fashion watch': 'ساعة موضة',
    'smart watch': 'ساعة ذكية',
    'mini crossbody': 'حقيبة كروس صغيرة',
    'quilted crossbody': 'حقيبة كروس مبطنة',
    'camera bag': 'حقيبة كاميرا',
    'top handle': 'مقبض علوي',
    'shoulder bag': 'حقيبة كتف',
    'tote bag': 'حقيبة توت',
    'mini backpack': 'حقيبة ظهر صغيرة',
    'laptop backpack': 'حقيبة لابتوب',
    'travel backpack': 'حقيبة سفر',
    'card holder': 'حافظة بطاقات',
    'zip wallet': 'محفظة بسحاب',
    'folding wallet': 'محفظة قابلة للطي',
    'handbags': 'حقائب يد',
    'crossbody bags': 'حقائب كروس',
    'backpacks': 'حقائب ظهر',
    'wallets': 'محافظ',
    'travel bags': 'حقائب سفر',
    'phone case': 'غطاء هاتف',
    'phone cases': 'أغطية هواتف',
    'cable': 'كيبل',
    'charger': 'شاحن',
    'ring holder': 'حامل حلقي',
    'earbuds': 'سماعات أذن',
    'headphones': 'سماعات رأس',
    'speakers': 'مكبرات صوت',
    'tracker': 'متعقب',
    'portable device': 'جهاز محمول',
    'audio': 'صوتيات',
    'smart devices': 'أجهزة ذكية',
    'tablets': 'أجهزة لوحية',
    'controller': 'ذراع تحكم',
    'keyboard': 'لوحة مفاتيح',
    'mouse': 'فأرة',
    'fashion deals': 'عروض الأزياء',
    'beauty deals': 'عروض الجمال',
    'home deals': 'عروض المنزل',
    'last chance': 'الفرصة الأخيرة',
    'end of season': 'نهاية الموسم',
    'final price': 'السعر النهائي',
    '2-piece set': 'طقم قطعتين',
    '3-piece bundle': 'باقة ثلاث قطع',
    'gift bundle': 'باقة هدايا',
    'summer picks': 'اختيارات الصيف',
    'holiday picks': 'اختيارات العطلات',
    'back to school': 'العودة إلى المدرسة',
    'educational toys': 'ألعاب تعليمية',
    'soft toys': 'ألعاب ناعمة',
    'outdoor toys': 'ألعاب خارجية',
    'games': 'ألعاب',
  });
}

String localizedColorName(BuildContext context, String value) {
  return _localizedCatalogValue(context, value, const {
    'black': 'أسود',
    'white': 'أبيض',
    'ivory': 'عاجي',
    'beige': 'بيج',
    'brown': 'بني',
    'grey': 'رمادي',
    'red': 'أحمر',
    'pink': 'وردي',
    'blue': 'أزرق',
    'navy': 'كحلي',
    'green': 'أخضر',
    'yellow': 'أصفر',
    'orange': 'برتقالي',
    'purple': 'بنفسجي',
    'gold': 'ذهبي',
    'silver': 'فضي',
  });
}

String localizedSizeName(BuildContext context, String value) {
  return _localizedCatalogValue(context, value, const {
    'one size': 'مقاس واحد',
  });
}

String _localizedCatalogValue(
  BuildContext context,
  String value,
  Map<String, String> arabicValues,
) {
  if (Localizations.localeOf(context).languageCode != 'ar') {
    return value;
  }
  return arabicValues[value.toLowerCase()] ?? value;
}
